pgver = '11' # pg version to use
vm_prefix = 'c_pgbr_c7'

Vagrant.configure(2) do |config|

	pgdata = "/var/lib/pgsql/#{pgver}/data"

	# https://vagrantcloud.com/search.
    config.vm.box = 'centos/7'

    # hardware and host settings
    config.vm.provider 'libvirt' do |lv|
        lv.cpus = 1
        lv.memory = 512
        lv.default_prefix = vm_prefix
	end

	# don't mind about insecure ssh key
    config.ssh.insert_key = false

    # build pgsql-srv instance
    config.vm.provision 'pgsql', type: 'shell',
        path: 'provision/pgsql.bash',
        args: [ pgver, pgdata ]

    # pgbackrest local setup. Use "vagrant up --provision-with=pgbackrest_local"
    config.vm.provision 'pgbackrest_local', type: 'shell',
    	path: 'provision/pgbackrest_local.bash',
        args: [ pgver, pgdata ],
        run: 'never'

    # check_pgbackrest install. Use "vagrant up --provision-with=check_pgbackrest"
    config.vm.provision 'check_pgbackrest', type: 'shell',
    	path: 'provision/check_pgbackrest.bash',
        run: 'never'

	# don't share the default vagrant folder
	config.vm.synced_folder ".", "/vagrant", disabled: true

	# copy check_pgbackrest directory
    config.vm.synced_folder '..', '/check_pgbackrest', type: 'rsync',
    	owner: 'root', group: 'root',
        rsync__args: [ "--verbose", "--archive", "--delete", "--copy-links", "--no-perms" ]
end