vm_prefix = 'c_pgbr_c7'

Vagrant.configure(2) do |config|
    config.vm.box = 'centos/7'

    # hardware and host settings
    config.vm.provider 'libvirt' do |lv|
        lv.cpus = 1
        lv.memory = 512
        lv.default_prefix = vm_prefix
	end

	# don't mind about insecure ssh key
    config.ssh.insert_key = false

    # don't share the default vagrant folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # mount check_pgbackrest path for testing
    config.vm.synced_folder "..", "/check_pgbackrest", nfs_udp: false

    # set node name
    config.vm.define "build-srv" do |node|
        node.vm.hostname = 'build-rpm-check-pgbackrest'
    end

    # build check_pgbackrest rpm
    config.vm.provision 'check_pgbackrest', type: 'shell', path: 'provision/check_pgbackrest.bash'
end